/**
 * The driver settlement statement.
 *
 * This sheet is filed as payroll and handed to a driver, so the tests read the
 * generated bytes back rather than trusting the template: the arithmetic shown
 * next to each line, the transliteration of the lane arrow, and the sign-off
 * wording are all things a reader sees and a regression would silently change.
 */
import { buildSettlementStatement, type SettlementStatementInput } from '../../src/modules/documents/pdf.templates';
import { toEmbeddableImage } from '../../src/modules/pdf/pdf.images';

/** Pull the text a reader would show, straight out of the content streams. */
function extractText(pdf: Buffer): string {
  const raw = pdf.toString('latin1');
  const pieces: string[] = [];
  const pattern = /\(((?:\\.|[^\\()])*)\)\s*Tj/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(raw)) !== null) {
    const body = match[1] as string;
    pieces.push(
      body
        .replace(/\\([0-7]{3})/g, (_, oct: string) => String.fromCharCode(Number.parseInt(oct, 8)))
        .replace(/\\([\\()])/g, '$1'),
    );
  }
  return pieces.join('\n');
}

/** Every text showing, with the x it was placed at, in document order. */
function showings(pdf: Buffer): Array<{ text: string; x: number; y: number }> {
  const raw = pdf.toString('latin1');
  const out: Array<{ text: string; x: number; y: number }> = [];
  const pattern = /1 0 0 1 (-?[\d.]+) (-?[\d.]+) Tm \(((?:\\.|[^\\()])*)\) Tj/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(raw)) !== null) {
    out.push({ x: Number(match[1]), y: Number(match[2]), text: (match[3] as string) });
  }
  return out;
}

/** A 1×1 baseline JPEG — the same shape the signature pad uploads. */
const JPEG = Buffer.from(
  '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==',
  'base64',
);

function statement(overrides: Partial<SettlementStatementInput> = {}): SettlementStatementInput {
  const amount = 'CA$239.13';
  return {
    statementNumber: 'ST-3F9A21C4',
    issuedAt: new Date('2026-09-14T12:00:00.000Z'),
    carrier: { name: 'Northline Carriers', mc: 'MC548616', usdot: 'USDOT 3120994' },
    driver: { name: 'Maria Chen', note: '$0.58 / mi' },
    periodLabel: 'Sep 7 – 13, 2026',
    periodFrom: 'Sep 7, 2026',
    periodTo: 'Sep 13, 2026',
    payLabel: '$0.58 / mi',
    lines: [
      {
        deliveredAt: '2026-09-08T18:00:00.000Z',
        reference: 'LW-1001',
        lane: 'QC → ON',
        basis: '412.3 mi × $0.58/mi',
        detentionBasis: '2.5 h detention × $60.00/h',
        amount,
      },
      {
        deliveredAt: '2026-09-10T18:00:00.000Z',
        reference: 'LW-1002',
        lane: 'ON → QC',
        basis: '418.2 mi × $0.58/mi',
        detentionBasis: null,
        amount: 'CA$242.56',
      },
    ],
    totals: [
      { label: "Pay — 2 loads ($0.58 / mi)", amount: 'CA$481.69' },
      { label: 'Detention — 2.5 h', amount: 'CA$150.00' },
    ],
    totalLabel: 'Total pay due',
    total: 'CA$631.69',
    notes: [],
    openQueries: [],
    signoff: 'I have reviewed the loads and the total pay of $631.69 for Sep 7 – 13, 2026.',
    driverSignature: null,
    carrierSignature: null,
    ...overrides,
  };
}

describe('settlement statement', () => {
  it('prints the period, the loads and the arithmetic behind each one', () => {
    const text = extractText(buildSettlementStatement(statement()));
    expect(text).toContain('SETTLEMENT STATEMENT');
    expect(text).toContain('ST-3F9A21C4');
    // An en dash prints as a plain hyphen: the built-in fonts cover WinAnsi and
    // a "-" is what the encoder substitutes.
    expect(text).toContain('Sep 7 - 13, 2026');
    expect(text).toContain('Maria Chen');
    expect(text).toContain('412.3 mi × $0.58/mi');
    expect(text).toContain('2.5 h detention × $60.00/h');
    expect(text).toContain('LW-1001');
    expect(text).toContain('LW-1002');
    expect(text).toContain('CA$239.13');
    expect(text).toContain('CA$631.69');
    expect(text).toContain('HOW THIS STATEMENT WAS WORKED OUT');
  });

  // The built-in fonts have no arrow and the encoder would otherwise print "?",
  // which on a payroll document reads like a missing value.
  it('transliterates the lane arrow instead of printing a question mark', () => {
    const text = extractText(buildSettlementStatement(statement()));
    expect(text).toContain('QC -> ON');
    expect(text).toContain('ON -> QC');
    expect(text).not.toMatch(/QC \? ON/);
  });

  it('right-aligns every amount on the same column', () => {
    const rows = showings(buildSettlementStatement(statement()));
    const amounts = rows.filter((r) => r.text === 'CA$239.13' || r.text === 'CA$242.56');
    expect(amounts).toHaveLength(2);
    expect(amounts[0].x).toBe(amounts[1].x);
  });

  it('prints a blank rule when nobody has signed, and the capture when they have', () => {
    const unsigned = extractText(buildSettlementStatement(statement()));
    expect(unsigned).toContain('Not signed');

    const asset = toEmbeddableImage(JPEG, 'image/jpeg');
    expect(asset.ok).toBe(true);
    const signed = buildSettlementStatement(
      statement({
        driverSignature: {
          role: 'DRIVER',
          signerName: 'Maria Chen',
          signedAt: new Date('2026-09-14T13:05:00.000Z'),
          asset: asset.ok ? asset : null,
        },
      }),
    );
    const text = extractText(signed);
    expect(text).toContain('Maria Chen');
    expect(text).toContain('Signed Sep 14, 2026 13:05');
    // The drawn mark is embedded, so the driver box is not blank — only the
    // carrier's, which nobody has signed yet.
    expect(signed.toString('latin1')).toContain('/Subtype /Image');
    expect((text.match(/Not signed/g) ?? []).length).toBe(1);
  });

  it('discloses open queries rather than asserting agreement over them', () => {
    const text = extractText(
      buildSettlementStatement(
        statement({
          openQueries: ['PD-3F9A21C4 — LW-1001 · QC -> ON · 412.3 mi × $0.58/mi → $239.13'],
          signoff:
            'I have reviewed the loads and the total pay of $631.69 for Sep 7 – 13, 2026. I have 1 pay query still open with the office.',
        }),
      ),
    );
    expect(text).toContain('OPEN PAY QUERIES');
    expect(text).toContain('PD-3F9A21C4');
    expect(text).toContain('412.3 mi × $0.58/mi');
    expect(text).toContain('1 pay query still open');
    expect(text).toContain('not final until these are settled');
  });

  it('carries the notes when a period has gaps worth explaining', () => {
    const text = extractText(
      buildSettlementStatement(
        statement({ notes: ['1 delivered load could not be priced and is shown at $0.00.'] }),
      ),
    );
    expect(text).toContain('NOTES ON THIS PERIOD');
    expect(text).toContain('could not be priced');
  });

  it('breaks a long period onto more pages rather than over the footer', () => {
    const lines = Array.from({ length: 45 }, (_, i) => ({
      deliveredAt: '2026-09-08T18:00:00.000Z',
      reference: `LW-${1000 + i}`,
      lane: 'QC → ON',
      basis: '412.3 mi × $0.58/mi',
      detentionBasis: null,
      amount: 'CA$239.13',
    }));
    const pdf = buildSettlementStatement(statement({ lines }));
    const pages = (pdf.toString('latin1').match(/\/Type \/Page /g) ?? []).length;
    expect(pages).toBeGreaterThan(1);
    // The footer stamps every page once the content is final.
    const text = extractText(pdf);
    expect(text).toContain(`Page 1 of ${pages}`);
    expect(text).toContain(`Page ${pages} of ${pages}`);
  });
});
